version: '3.8'
services:
  mongoDB2:
    image: mongo:6.0
    restart: always
    container_name: mongoDB2
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: component-2-2:latest
    container_name: component-2-2
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongoDB2:27017/db
      - SPRING_GRAPHQL_SCHEMA_LOCATION=classpath:/graphql/
    depends_on:
      - mongoDB2

volumes:
  mongo_data:
